name: Build and Upload Docker Image

on:
  repository_dispatch:
    types: [trigger-build-and-upload]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ github.event.client_payload.image_name }}
        docker build -t your_dockerhub_username/$IMAGE_NAME .
        docker push your_dockerhub_username/$IMAGE_NAME

    - name: Login to Aliyun
      run: |
        docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-shanghai.aliyuncs.com

    - name: Tag and push to Aliyun
      run: |
        IMAGE_NAME=${{ github.event.client_payload.image_name }}
        docker tag your_dockerhub_username/$IMAGE_NAME registry.cn-shanghai.aliyuncs.com/your_aliyun_repo/$IMAGE_NAME
        docker push registry.cn-shanghai.aliyuncs.com/your_aliyun_repo/$IMAGE_NAME
