name: Docker

on:
  workflow_dispatch:
    inputs:
      image_info:
        description: 'Docker image information'
        required: true
  push:
    branches: [ main ]

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        image_info="${{ github.event.inputs.image_info }}"
        echo "Processing image: $image_info"
        docker pull $image_info
        echo "pull finish"
        namespace=$(echo "$image_info" | awk -F'/' '{print $1}')
        echo "this is namespase: $namespace"
        image_name_tag=$(echo "$image_info" | awk -F'/' '{print $2}')
        echo "this is image_name_tag: $image_name_tag"
        # 删除末尾可能的下划线
        image_name_tag="${image_name_tag%_}"
        echo "this is image_name_tag2: image_name_tag"
        new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/${namespace}_${image_name_tag}"
        echo "this is new name: $new_image"
        echo "this is re-tag:"
        docker tag $image_info $new_image
        echo "this is pushing:"
        docker push $new_image
        echo "this is rmi image_info"
        docker rmi $image_info
        echo "this is rmi new_image"
        docker rmi $new_image
