name: Pull and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to pull and push'
        required: true
        default: 'nginx:latest'

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  pull_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Registry
      run: |
        echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_REGISTRY_USER }}" --password-stdin ${{ secrets.ALIYUN_REGISTRY }}

    - name: Pull and Push Docker Image
      run: |
        image_name=${{ github.event.inputs.image }}
        docker pull $image_name
        image_basename=$(basename $image_name)
        aliyun_image="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/$image_basename"
        docker tag $image_name $aliyun_image
        docker push $aliyun_image
